// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using fix_my_device_backend.Data;

#nullable disable

namespace backend_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("fix_my_device_backend.Models.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FreeStorage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GraphicsCard")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GraphicsMemory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InstalledOn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InstalledRam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastSeenAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OsBuild")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Processor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProcessorSpeed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SystemType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TotalStorage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsableRam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsedStorage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("WindowsEdition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WindowsVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DeviceId")
                        .IsUnique();

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("fix_my_device_backend.Models.DeviceDrive", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeviceEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("DriveLetter")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DriveType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileSystem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FreeSpace")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TotalSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsedSpace")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VolumeLabel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeviceEntityId");

                    b.ToTable("DeviceDrives");
                });

            modelBuilder.Entity("fix_my_device_backend.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("fix_my_device_backend.Models.Device", b =>
                {
                    b.HasOne("fix_my_device_backend.Models.User", "User")
                        .WithMany("Devices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("fix_my_device_backend.Models.DeviceDrive", b =>
                {
                    b.HasOne("fix_my_device_backend.Models.Device", "Device")
                        .WithMany("Drives")
                        .HasForeignKey("DeviceEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("fix_my_device_backend.Models.Device", b =>
                {
                    b.Navigation("Drives");
                });

            modelBuilder.Entity("fix_my_device_backend.Models.User", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
